#include "sqlparser/api/root_handler.h"

#include <stdio.h>

int api_handle_root(const HttpRequest *request, const ApiContext *context, HttpResponse *response) {
    static const char *page =
        "<!doctype html>\n"
        "<html lang=\"ko\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "  <title>SQL API Console</title>\n"
        "  <style>\n"
        "    :root {\n"
        "      --bg: #f3f4f6;\n"
        "      --panel: #ffffff;\n"
        "      --border: #d1d5db;\n"
        "      --text: #111827;\n"
        "      --muted: #6b7280;\n"
        "      --console: #111111;\n"
        "      --console-text: #f3f4f6;\n"
        "      --ok: #166534;\n"
        "      --ok-bg: #dcfce7;\n"
        "      --running: #1d4ed8;\n"
        "      --running-bg: #dbeafe;\n"
        "      --error: #b91c1c;\n"
        "      --error-bg: #fee2e2;\n"
        "    }\n"
        "    * { box-sizing: border-box; }\n"
        "    body {\n"
        "      margin: 0;\n"
        "      min-height: 100vh;\n"
        "      background: var(--bg);\n"
        "      color: var(--text);\n"
        "      font-family: \"Courier New\", monospace;\n"
        "    }\n"
        "    .page {\n"
        "      max-width: 960px;\n"
        "      margin: 0 auto;\n"
        "      padding: 24px 16px 40px;\n"
        "    }\n"
        "    h1 {\n"
        "      margin: 0 0 8px;\n"
        "      font-size: 24px;\n"
        "      font-weight: 700;\n"
        "    }\n"
        "    .sub {\n"
        "      margin: 0 0 16px;\n"
        "      color: var(--muted);\n"
        "      font-size: 14px;\n"
        "    }\n"
        "    .panel {\n"
        "      background: var(--panel);\n"
        "      border: 1px solid var(--border);\n"
        "      border-radius: 10px;\n"
        "      padding: 16px;\n"
        "    }\n"
        "    .endpoints {\n"
        "      margin: 0 0 16px;\n"
        "      color: var(--muted);\n"
        "      font-size: 13px;\n"
        "      line-height: 1.6;\n"
        "    }\n"
        "    textarea {\n"
        "      width: 100%%;\n"
        "      min-height: 180px;\n"
        "      resize: vertical;\n"
        "      padding: 14px;\n"
        "      border: 1px solid var(--border);\n"
        "      border-radius: 8px;\n"
        "      background: #ffffff;\n"
        "      color: var(--text);\n"
        "      font: 14px/1.6 \"Courier New\", monospace;\n"
        "    }\n"
        "    textarea[readonly] {\n"
        "      background: #f3f4f6;\n"
        "      cursor: wait;\n"
        "    }\n"
        "    .toolbar {\n"
        "      display: flex;\n"
        "      flex-wrap: wrap;\n"
        "      gap: 10px;\n"
        "      align-items: center;\n"
        "      margin-top: 12px;\n"
        "    }\n"
        "    button {\n"
        "      appearance: none;\n"
        "      border: 1px solid #374151;\n"
        "      border-radius: 8px;\n"
        "      padding: 10px 14px;\n"
        "      background: #111827;\n"
        "      color: #f9fafb;\n"
        "      font: 700 14px/1 \"Courier New\", monospace;\n"
        "      cursor: pointer;\n"
        "    }\n"
        "    button:disabled {\n"
        "      opacity: 0.6;\n"
        "      cursor: wait;\n"
        "    }\n"
        "    .hint {\n"
        "      color: var(--muted);\n"
        "      font-size: 12px;\n"
        "    }\n"
        "    .status {\n"
        "      margin-top: 16px;\n"
        "      min-height: 44px;\n"
        "      padding: 10px 12px;\n"
        "      border-radius: 8px;\n"
        "      border: 1px solid var(--border);\n"
        "      font-size: 14px;\n"
        "      line-height: 1.5;\n"
        "      white-space: pre-wrap;\n"
        "    }\n"
        "    .status.ok {\n"
        "      background: var(--ok-bg);\n"
        "      color: var(--ok);\n"
        "      border-color: rgba(20, 83, 45, 0.16);\n"
        "    }\n"
        "    .status.running {\n"
        "      background: var(--running-bg);\n"
        "      color: var(--running);\n"
        "      border-color: rgba(29, 78, 216, 0.18);\n"
        "    }\n"
        "    .status.error {\n"
        "      background: var(--error-bg);\n"
        "      color: var(--error);\n"
        "      border-color: #fecaca;\n"
        "    }\n"
        "    .console {\n"
        "      margin: 12px 0 0;\n"
        "      min-height: 260px;\n"
        "      padding: 14px;\n"
        "      overflow: auto;\n"
        "      border-radius: 8px;\n"
        "      background: var(--console);\n"
        "      color: var(--console-text);\n"
        "      border: 1px solid #1f2937;\n"
        "      font: 14px/1.6 \"Courier New\", monospace;\n"
        "      white-space: pre-wrap;\n"
        "      word-break: break-word;\n"
        "    }\n"
        "    .meta {\n"
        "      display: grid;\n"
        "      gap: 10px;\n"
        "      grid-template-columns: repeat(3, minmax(0, 1fr));\n"
        "      margin-top: 12px;\n"
        "    }\n"
        "    .meta-item {\n"
        "      padding: 10px 12px;\n"
        "      background: #f9fafb;\n"
        "      border: 1px solid var(--border);\n"
        "      border-radius: 8px;\n"
        "      font-size: 13px;\n"
        "    }\n"
        "    .meta-key {\n"
        "      display: block;\n"
        "      margin-bottom: 4px;\n"
        "      color: var(--muted);\n"
        "      font-size: 12px;\n"
        "    }\n"
        "    @media (max-width: 640px) {\n"
        "      .page { padding: 16px 12px 24px; }\n"
        "      .panel { padding: 12px; }\n"
        "      .meta { grid-template-columns: 1fr; }\n"
        "    }\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <div class=\"page\">\n"
        "    <div class=\"panel\">\n"
        "      <h1>SQL API Console</h1>\n"
        "      <p class=\"sub\">POST /query 를 호출하는 간단한 테스트 화면입니다.</p>\n"
        "      <div class=\"endpoints\">GET /health<br>POST /query<br>workers: %d / queue_depth: %d</div>\n"
        "      <textarea id=\"sql-input\" spellcheck=\"false\">SELECT name FROM student WHERE id = 1;</textarea>\n"
        "      <div class=\"toolbar\">\n"
        "        <button id=\"run-button\">Run</button>\n"
        "        <span class=\"hint\">Ctrl + Enter 또는 Cmd + Enter / help, .help, --help</span>\n"
        "      </div>\n"
        "      <div id=\"status\" class=\"status ok\">ready</div>\n"
        "      <div class=\"meta\">\n"
        "        <div class=\"meta-item\"><span class=\"meta-key\">statement_type</span><span id=\"statement-type\">-</span></div>\n"
        "        <div class=\"meta-item\"><span class=\"meta-key\">summary</span><span id=\"summary\">-</span></div>\n"
        "        <div class=\"meta-item\"><span class=\"meta-key\">elapsed_ms (cpu)</span><span id=\"elapsed\">-</span></div>\n"
        "        <div class=\"meta-item\"><span class=\"meta-key\">wall_elapsed_ms</span><span id=\"wall-elapsed\">-</span></div>\n"
        "      </div>\n"
        "      <pre id=\"console\" class=\"console\">waiting for query execution...</pre>\n"
        "    </div>\n"
        "  </div>\n"
        "  <script>\n"
        "    const sqlInput = document.getElementById('sql-input');\n"
        "    const runButton = document.getElementById('run-button');\n"
        "    const statusBox = document.getElementById('status');\n"
        "    const consoleBox = document.getElementById('console');\n"
        "    const statementType = document.getElementById('statement-type');\n"
        "    const summary = document.getElementById('summary');\n"
        "    const elapsed = document.getElementById('elapsed');\n"
        "    const wallElapsed = document.getElementById('wall-elapsed');\n"
        "    const defaultRunButtonText = runButton.textContent;\n"
        "\n"
        "    function setStatus(kind, message) {\n"
        "      statusBox.className = 'status ' + kind;\n"
        "      statusBox.textContent = message;\n"
        "    }\n"
        "\n"
        "    function setRunningState(isRunning) {\n"
        "      runButton.disabled = isRunning;\n"
        "      runButton.textContent = isRunning ? 'Running...' : defaultRunButtonText;\n"
        "      sqlInput.readOnly = isRunning;\n"
        "    }\n"
        "\n"
        "    function setResult(data) {\n"
        "      statementType.textContent = data.statement_type || '-';\n"
        "      summary.textContent = data.summary || '-';\n"
        "      elapsed.textContent = typeof data.elapsed_ms === 'number' ? data.elapsed_ms.toFixed(3) + ' ms' : '-';\n"
        "      wallElapsed.textContent = typeof data.wall_elapsed_ms === 'number' ? data.wall_elapsed_ms.toFixed(3) + ' ms' : '-';\n"
        "      consoleBox.textContent = data.output && data.output.length > 0 ? data.output : '(no output)';\n"
        "    }\n"
        "\n"
        "    function buildErrorHint(error) {\n"
        "      const code = error && error.code ? error.code : '';\n"
        "      const message = error && error.message ? error.message : '';\n"
        "      if (code === 'UNSUPPORTED_SQL' && message.indexOf('SQL must start with SELECT or INSERT') !== -1) {\n"
        "        return 'SELECT 또는 INSERT로 시작해야 합니다. SELEC처럼 첫 키워드에 오타가 없는지 확인하세요.';\n"
        "      }\n"
        "      if (code === 'SQL_PARSE_ERROR') {\n"
        "        return '세미콜론 누락, FROM 절 누락, 컬럼/테이블 이름 누락 같은 문법 오류인지 확인하세요.';\n"
        "      }\n"
        "      if (code === 'INVALID_SQL_ARGUMENT' && message.indexOf('WHERE id = ... requires an integer value.') !== -1) {\n"
        "        return 'WHERE id = ... 는 정수만 허용합니다. 문자열 비교가 필요하면 일반 컬럼 WHERE를 사용하세요.';\n"
        "      }\n"
        "      if (code === 'INVALID_SQL_ARGUMENT' && message.indexOf('SQL statement must not be blank') !== -1) {\n"
        "        return '빈 입력은 실행되지 않습니다. SELECT 또는 INSERT 문장을 입력하세요.';\n"
        "      }\n"
        "      return '';\n"
        "    }\n"
        "\n"
        "    function setError(data) {\n"
        "      const error = data && data.error ? data.error : {};\n"
        "      const baseMessage = error.message || 'request failed';\n"
        "      const hint = buildErrorHint(error);\n"
        "      statementType.textContent = '-';\n"
        "      summary.textContent = error.code || '-';\n"
        "      elapsed.textContent = '-';\n"
        "      wallElapsed.textContent = '-';\n"
        "      consoleBox.textContent = hint ? baseMessage + '\\n\\n추가 안내:\\n' + hint : baseMessage;\n"
        "    }\n"
        "\n"
        "    function showHelp() {\n"
        "      setStatus('ok', 'help');\n"
        "      statementType.textContent = 'client';\n"
        "      summary.textContent = 'HELP';\n"
        "      elapsed.textContent = '-';\n"
        "      wallElapsed.textContent = '-';\n"
        "      consoleBox.textContent = [\n"
        "        'SQL API Console',\n"
        "        '',\n"
        "        'supported SQL:',\n"
        "        '  SELECT ...',\n"
        "        '  INSERT ...',\n"
        "        '',\n"
        "        'examples:',\n"
        "        '  SELECT name FROM student WHERE id = 1;',\n"
        "        '  SELECT * FROM student WHERE age = 25;',\n"
        "        '',\n"
        "        'special commands:',\n"
        "        '  help',\n"
        "        '  .help',\n"
        "        '  --help',\n"
        "      ].join('\\n');\n"
        "    }\n"
        "\n"
        "    async function runQuery() {\n"
        "      if (runButton.disabled) {\n"
        "        return;\n"
        "      }\n"
        "      const sql = sqlInput.value;\n"
        "      const normalized = sql.trim();\n"
        "      if (normalized === 'help' || normalized === '.help' || normalized === '--help') {\n"
        "        showHelp();\n"
        "        return;\n"
        "      }\n"
        "      if (!normalized) {\n"
        "        setStatus('error', 'empty sql is not allowed');\n"
        "        statementType.textContent = '-';\n"
        "        summary.textContent = 'CLIENT_VALIDATION';\n"
        "        elapsed.textContent = '-';\n"
        "        wallElapsed.textContent = '-';\n"
        "        consoleBox.textContent = 'enter a SQL statement';\n"
        "        return;\n"
        "      }\n"
        "      setRunningState(true);\n"
        "      setStatus('running', 'running');\n"
        "      consoleBox.textContent = 'running...';\n"
        "      try {\n"
        "        const response = await fetch('/query', {\n"
        "          method: 'POST',\n"
        "          headers: { 'Content-Type': 'application/json' },\n"
        "          body: JSON.stringify({ sql })\n"
        "        });\n"
        "        const data = await response.json();\n"
        "        if (!response.ok || !data.ok) {\n"
        "          setStatus('error', 'error: ' + (data.error ? data.error.code : response.status));\n"
        "          setError(data);\n"
        "          return;\n"
        "        }\n"
        "        setStatus('ok', 'ok');\n"
        "        setResult(data);\n"
        "      } catch (error) {\n"
        "        setStatus('error', 'network error');\n"
        "        statementType.textContent = '-';\n"
        "        summary.textContent = 'CLIENT_ERROR';\n"
        "        elapsed.textContent = '-';\n"
        "        wallElapsed.textContent = '-';\n"
        "        consoleBox.textContent = error.message;\n"
        "      } finally {\n"
        "        setRunningState(false);\n"
        "      }\n"
        "    }\n"
        "\n"
        "    runButton.addEventListener('click', runQuery);\n"
        "    sqlInput.addEventListener('keydown', function (event) {\n"
        "      if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') {\n"
        "        runQuery();\n"
        "      }\n"
        "    });\n"
        "  </script>\n"
        "</body>\n"
        "</html>\n";
    char body[16384];
    int written;

    if (request->body_length > 0) {
        return http_response_set_error(response,
                                       SQL_ENGINE_ERROR_INVALID_JSON,
                                       "GET / must not include a request body");
    }

    written = snprintf(body,
                       sizeof(body),
                       page,
                       context->worker_count,
                       context->queue_depth);
    if (written < 0 || (size_t)written >= sizeof(body)) {
        return 0;
    }

    return http_response_set_html(response, 200, body);
}
